export const MUSCLE_NAMES = {
  front: {
    'muscle-2': { ru: 'Голова', en: 'Head' },
    'muscle-3': { ru: 'Правый квадрицепс', en: 'Right quadriceps' },
    'muscle-4': { ru: 'Правый привод', en: 'Right adductor' },
    'muscle-5': { ru: 'Правая стопа', en: 'Right foot' },
    'muscle-6': { ru: 'Правый голеностоп', en: 'Right ankle' },
    'muscle-7': { ru: 'Правая голень', en: 'Right shin' },
    'muscle-8': { ru: 'Правая рука', en: 'Right arm' },
    'muscle-9': { ru: 'Правый бицепс', en: 'Right biceps' },
    'muscle-10': { ru: 'Левый бок (верх)', en: 'Left side (upper)' },
    'muscle-11': { ru: 'Правое плечо', en: 'Right shoulder' },
    'muscle-12': { ru: 'Живот', en: 'Abdomen' },
    'muscle-13': { ru: 'Нижняя часть живота', en: 'Lower abdomen' },
    'muscle-14': { ru: 'Правый бок (низ)', en: 'Right side (lower)' },
    'muscle-15': { ru: 'Правое колено', en: 'Right knee' },
    'muscle-16': { ru: 'Правый бок', en: 'Right side' },
    'muscle-17': { ru: 'Левый бок (низ)', en: 'Left side (lower)' },
    'muscle-18': { ru: 'Правая грудь', en: 'Right chest' },
    'muscle-19': { ru: 'Правый кисть', en: 'Right hand' },
    'muscle-20': { ru: 'Левая грудь', en: 'Left chest' },
    'muscle-21': { ru: 'Левое плечо', en: 'Left shoulder' },
    'muscle-22': { ru: 'Левый бицепс', en: 'Left biceps' },
    'muscle-23': { ru: 'Левая рука', en: 'Left arm' },
    'muscle-24': { ru: 'Левое колено', en: 'Left knee' },
    'muscle-25': { ru: 'Левая голень', en: 'Left shin' },
    'muscle-26': { ru: 'Левый голеностоп', en: 'Left ankle' },
    'muscle-27': { ru: 'Левая стопа', en: 'Left foot' },
    'muscle-28': { ru: 'Горло', en: 'Throat' },
    'muscle-29': { ru: 'Левая кисть', en: 'Left hand' },
    'muscle-30': { ru: 'Левый привод', en: 'Left adductor' },
    'muscle-31': { ru: 'Левый квадрицепс', en: 'Left quadriceps' },
    'muscle-32': { ru: 'Голова', en: 'Head' }
  },
  back: {
    'muscle-3': { ru: 'Левое плечо', en: 'Left shoulder' },
    'muscle-4': { ru: 'Левая лопатка', en: 'Left scapula' },
    'muscle-5': { ru: 'Левая часть спины', en: 'Left back' },
    'muscle-6': { ru: 'Левая икроножная', en: 'Left calf' },
    'muscle-7': { ru: 'Левая пятка', en: 'Left heel' },
    'muscle-8': { ru: 'Левый ахил', en: 'Left Achilles' },
    'muscle-9': { ru: 'Левый хамстринг', en: 'Left hamstring' },
    'muscle-10': { ru: 'Левый трицепс', en: 'Left triceps' },
    'muscle-11': { ru: 'Левый локоть', en: 'Left elbow' },
    'muscle-12': { ru: 'Верхняя часть спины', en: 'Upper back' },
    'muscle-13': { ru: 'Правое плечо', en: 'Right shoulder' },
    'muscle-14': { ru: 'Правая лопатка', en: 'Right scapula' },
    'muscle-15': { ru: 'Правая часть спины', en: 'Right back' },
    'muscle-16': { ru: 'Правая икроножная', en: 'Right calf' },
    'muscle-17': { ru: 'Правая пятка', en: 'Right heel' },
    'muscle-18': { ru: 'Правый ахил', en: 'Right Achilles' },
    'muscle-19': { ru: 'Правый хамстринг', en: 'Right hamstring' },
    'muscle-20': { ru: 'Правый трицепс', en: 'Right triceps' },
    'muscle-21': { ru: 'Правый локоть', en: 'Right elbow' },
    'muscle-22': { ru: 'Левая ягодица', en: 'Left glute' },
    'muscle-23': { ru: 'Правая ягодица', en: 'Right glute' },
    'muscle-24': { ru: 'Нижняя часть спины', en: 'Lower back' },
    'muscle-25': { ru: 'Шея', en: 'Neck' }
  }
} as const;

// Популярные типы фитнес-тестов
export const FITNESS_TEST_TYPES = [
  { value: 'anthropometry', label: 'Антропометрия' },
  { value: 'speed', label: 'Скорость' },
  { value: 'strength', label: 'Сила' },
  { value: 'endurance', label: 'Выносливость' },
  { value: 'agility', label: 'Ловкость' },
  { value: 'flexibility', label: 'Гибкость' },
  { value: 'other', label: 'Другое' },
];

// Популярные единицы измерения с расшифровками
export const FITNESS_TEST_UNITS = [
  { value: 'kg', label: 'кг', description: 'килограмм' },
  { value: 'cm', label: 'см', description: 'сантиметр' },
  { value: 'm', label: 'м', description: 'метр' },
  { value: 's', label: 'сек', description: 'секунда' },
  { value: 'min', label: 'мин', description: 'минута' },
  { value: 'ms', label: 'мс', description: 'миллисекунда' },
  { value: 'm_s', label: 'м/с', description: 'метр в секунду' },
  { value: 'km_h', label: 'км/ч', description: 'километр в час' },
  { value: 'reps', label: 'повторений', description: 'повторений' },
  { value: 'points', label: 'баллы', description: 'баллы' },
  { value: 'deg', label: '°', description: 'градусы' },
]; 