// Полный список стран для выбора национальности игрока
export const countries = [
  { code: 'RU', name: { ru: 'Россия', en: 'Russia' } },
  { code: 'AL', name: { ru: 'Албания', en: 'Albania' } },
  { code: 'GB-ENG', name: { ru: 'Англия', en: 'England' } },
  { code: 'BR', name: { ru: 'Бразилия', en: 'Brazil' } },
  { code: 'AR', name: { ru: 'Аргентина', en: 'Argentina' } },
  { code: 'ES', name: { ru: 'Испания', en: 'Spain' } },
  { code: 'IT', name: { ru: 'Италия', en: 'Italy' } },
  { code: 'DE', name: { ru: 'Германия', en: 'Germany' } },
  { code: 'FR', name: { ru: 'Франция', en: 'France' } },
  { code: 'NL', name: { ru: 'Нидерланды', en: 'Netherlands' } },
  { code: 'PT', name: { ru: 'Португалия', en: 'Portugal' } },
  { code: 'BE', name: { ru: 'Бельгия', en: 'Belgium' } },
  { code: 'UY', name: { ru: 'Уругвай', en: 'Uruguay' } },
  { code: 'CO', name: { ru: 'Колумбия', en: 'Colombia' } },
  { code: 'MX', name: { ru: 'Мексика', en: 'Mexico' } },
  { code: 'US', name: { ru: 'США', en: 'USA' } },
  { code: 'CA', name: { ru: 'Канада', en: 'Canada' } },
  { code: 'JP', name: { ru: 'Япония', en: 'Japan' } },
  { code: 'CN', name: { ru: 'Китай', en: 'China' } },
  { code: 'AU', name: { ru: 'Австралия', en: 'Australia' } },
  { code: 'KR', name: { ru: 'Корея', en: 'Korea' } },
  { code: 'EG', name: { ru: 'Египет', en: 'Egypt' } },
  { code: 'MA', name: { ru: 'Марокко', en: 'Morocco' } },
  { code: 'NG', name: { ru: 'Нигерия', en: 'Nigeria' } },
  { code: 'SN', name: { ru: 'Сенегал', en: 'Senegal' } },
  { code: 'GH', name: { ru: 'Гана', en: 'Ghana' } },
  { code: 'CM', name: { ru: 'Камерун', en: 'Cameroon' } },
  { code: 'DZ', name: { ru: 'Алжир', en: 'Algeria' } },
  { code: 'UA', name: { ru: 'Украина', en: 'Ukraine' } },
  { code: 'BY', name: { ru: 'Беларусь', en: 'Belarus' } },
  { code: 'KZ', name: { ru: 'Казахстан', en: 'Kazakhstan' } },
  { code: 'UZ', name: { ru: 'Узбекистан', en: 'Uzbekistan' } },
  { code: 'TJ', name: { ru: 'Таджикистан', en: 'Tajikistan' } },
  { code: 'KG', name: { ru: 'Киргизстан', en: 'Kyrgyzstan' } },
  { code: 'RS', name: { ru: 'Сербия', en: 'Serbia' } },
  { code: 'HR', name: { ru: 'Хорватия', en: 'Croatia' } },
  { code: 'SE', name: { ru: 'Швеция', en: 'Sweden' } },
  { code: 'DK', name: { ru: 'Дания', en: 'Denmark' } },
  { code: 'NO', name: { ru: 'Норвегия', en: 'Norway' } },
  { code: 'FI', name: { ru: 'Финляндия', en: 'Finland' } },
  { code: 'IS', name: { ru: 'Исландия', en: 'Iceland' } },
  { code: 'PL', name: { ru: 'Польша', en: 'Poland' } },
  { code: 'CZ', name: { ru: 'Чехия', en: 'Czech Republic' } },
  { code: 'SK', name: { ru: 'Словакия', en: 'Slovakia' } },
  { code: 'HU', name: { ru: 'Венгрия', en: 'Hungary' } },
  { code: 'AT', name: { ru: 'Австрия', en: 'Austria' } },
  { code: 'CH', name: { ru: 'Швейцария', en: 'Switzerland' } },
  { code: 'GR', name: { ru: 'Греция', en: 'Greece' } },
  { code: 'TR', name: { ru: 'Турция', en: 'Turkey' } },
  { code: 'RO', name: { ru: 'Румыния', en: 'Romania' } },
  { code: 'BG', name: { ru: 'Болгария', en: 'Bulgaria' } },
  { code: 'MD', name: { ru: 'Молдова', en: 'Moldova' } },
  { code: 'ME', name: { ru: 'Черногория', en: 'Montenegro' } },
  { code: 'BA', name: { ru: 'Босния и Герцеговина', en: 'Bosnia and Herzegovina' } },
  { code: 'AM', name: { ru: 'Армения', en: 'Armenia' } },
  { code: 'AZ', name: { ru: 'Азербайджан', en: 'Azerbaijan' } },
  { code: 'GE', name: { ru: 'Грузия', en: 'Georgia' } },
  { code: 'IR', name: { ru: 'Иран', en: 'Iran' } },
  { code: 'IQ', name: { ru: 'Ирак', en: 'Iraq' } },
  { code: 'SA', name: { ru: 'Саудовская Аравия', en: 'Saudi Arabia' } },
  { code: 'QA', name: { ru: 'Катар', en: 'Qatar' } },
  { code: 'AE', name: { ru: 'ОАЭ', en: 'UAE' } },
  { code: 'KW', name: { ru: 'Кувейт', en: 'Kuwait' } },
  { code: 'OM', name: { ru: 'Оман', en: 'Oman' } },
  { code: 'IL', name: { ru: 'Израиль', en: 'Israel' } },
  { code: 'IN', name: { ru: 'Индия', en: 'India' } },
  { code: 'PK', name: { ru: 'Пакистан', en: 'Pakistan' } },
  { code: 'BD', name: { ru: 'Бангладеш', en: 'Bangladesh' } },
  { code: 'CI', name: { ru: 'Кот-д\'Ивуар', en: 'Ivory Coast' } },
  { code: 'ZA', name: { ru: 'ЮАР', en: 'South Africa' } },
  { code: 'GN', name: { ru: 'Гвинея', en: 'Guinea' } },
  { code: 'ML', name: { ru: 'Мали', en: 'Mali' } },
  { code: 'BF', name: { ru: 'Буркина-Фасо', en: 'Burkina Faso' } },
  { code: 'TN', name: { ru: 'Тунис', en: 'Tunisia' } },
  { code: 'LR', name: { ru: 'Либерия', en: 'Liberia' } },
  { code: 'SD', name: { ru: 'Судан', en: 'Sudan' } },
  { code: 'ET', name: { ru: 'Эфиопия', en: 'Ethiopia' } },
  { code: 'KE', name: { ru: 'Кения', en: 'Kenya' } },
  { code: 'TZ', name: { ru: 'Танзания', en: 'Tanzania' } },
  { code: 'UG', name: { ru: 'Уганда', en: 'Uganda' } },
  { code: 'ZW', name: { ru: 'Зимбабве', en: 'Zimbabwe' } },
  { code: 'AO', name: { ru: 'Ангола', en: 'Angola' } },
  { code: 'PE', name: { ru: 'Перу', en: 'Peru' } },
  { code: 'CL', name: { ru: 'Чили', en: 'Chile' } },
  { code: 'EC', name: { ru: 'Эквадор', en: 'Ecuador' } },
  { code: 'VE', name: { ru: 'Венесуэла', en: 'Venezuela' } },
  { code: 'PY', name: { ru: 'Парагвай', en: 'Paraguay' } },
  { code: 'BO', name: { ru: 'Боливия', en: 'Bolivia' } },
  { code: 'CR', name: { ru: 'Коста-Рика', en: 'Costa Rica' } },
  { code: 'PA', name: { ru: 'Панама', en: 'Panama' } },
  { code: 'HN', name: { ru: 'Гондурас', en: 'Honduras' } },
  { code: 'SV', name: { ru: 'Сальвадор', en: 'El Salvador' } },
  { code: 'JM', name: { ru: 'Ямайка', en: 'Jamaica' } },
  { code: 'TH', name: { ru: 'Таиланд', en: 'Thailand' } },
  { code: 'VN', name: { ru: 'Вьетнам', en: 'Vietnam' } },
  { code: 'ID', name: { ru: 'Индонезия', en: 'Indonesia' } },
  { code: 'MY', name: { ru: 'Малайзия', en: 'Malaysia' } },
  { code: 'PH', name: { ru: 'Филиппины', en: 'Philippines' } },
  { code: 'NZ', name: { ru: 'Новая Зеландия', en: 'New Zealand' } },
  { code: 'HT', name: { ru: 'Гаити', en: 'Haiti' } },
  { code: 'MN', name: { ru: 'Монголия', en: 'Mongolia' } },
  { code: 'GB-SCT', name: { ru: 'Шотландия', en: 'Scotland' } },
  { code: 'GB-WLS', name: { ru: 'Уэльс', en: 'Wales' } },
  { code: 'GB-NIR', name: { ru: 'Северная Ирландия', en: 'Northern Ireland' } },
  { code: 'LU', name: { ru: 'Люксембург', en: 'Luxembourg' } },
  { code: 'FO', name: { ru: 'Фарерские острова', en: 'Faroe Islands' } },
  { code: 'AD', name: { ru: 'Андорра', en: 'Andorra' } },
  { code: 'MT', name: { ru: 'Мальта', en: 'Malta' } },
  { code: 'CY', name: { ru: 'Кипр', en: 'Cyprus' } },
  { code: 'MO', name: { ru: 'Макао', en: 'Macau' } },
  { code: 'HK', name: { ru: 'Гонконг', en: 'Hong Kong' } },
  { code: 'SG', name: { ru: 'Сингапур', en: 'Singapore' } },
  { code: 'ZM', name: { ru: 'Замбия', en: 'Zambia' } },
  { code: 'GA', name: { ru: 'Габон', en: 'Gabon' } },
  { code: 'MZ', name: { ru: 'Мозамбик', en: 'Mozambique' } },
  { code: 'BW', name: { ru: 'Ботсвана', en: 'Botswana' } },
  { code: 'MW', name: { ru: 'Малави', en: 'Malawi' } },
  { code: 'NA', name: { ru: 'Намибия', en: 'Namibia' } },
  { code: 'BJ', name: { ru: 'Бенин', en: 'Benin' } },
  { code: 'TG', name: { ru: 'Того', en: 'Togo' } },
  { code: 'TD', name: { ru: 'Чад', en: 'Chad' } },
  { code: 'CF', name: { ru: 'Центральноафриканская Республика', en: 'Central African Republic' } },
  { code: 'CG', name: { ru: 'Конго', en: 'Congo' } },
  { code: 'CD', name: { ru: 'Демократическая Республика Конго', en: 'Democratic Republic of the Congo' } },
  { code: 'SL', name: { ru: 'Сьерра-Леоне', en: 'Sierra Leone' } },
  { code: 'GM', name: { ru: 'Гамбия', en: 'Gambia' } },
  { code: 'CV', name: { ru: 'Кабо-Верде', en: 'Cape Verde' } },
  { code: 'MR', name: { ru: 'Мавритания', en: 'Mauritania' } },
  { code: 'MU', name: { ru: 'Маврикий', en: 'Mauritius' } },
  { code: 'SC', name: { ru: 'Сейшелы', en: 'Seychelles' } },
  { code: 'KM', name: { ru: 'Коморы', en: 'Comoros' } },
  { code: 'SO', name: { ru: 'Сомали', en: 'Somalia' } },
  { code: 'RW', name: { ru: 'Руанда', en: 'Rwanda' } },
  { code: 'BI', name: { ru: 'Бурунди', en: 'Burundi' } },
  { code: 'LS', name: { ru: 'Лесото', en: 'Lesotho' } },
  { code: 'SZ', name: { ru: 'Эсватини', en: 'Eswatini' } },
  { code: 'DJ', name: { ru: 'Джибути', en: 'Djibouti' } },
  { code: 'GW', name: { ru: 'Гвинея-Бисау', en: 'Guinea-Bissau' } },
  { code: 'GQ', name: { ru: 'Экваториальная Гвинея', en: 'Equatorial Guinea' } },
  { code: 'ST', name: { ru: 'Сан-Томе и Принсипи', en: 'Sao Tome and Principe' } },
  { code: 'ER', name: { ru: 'Эритрея', en: 'Eritrea' } },
  { code: 'LY', name: { ru: 'Ливия', en: 'Libya' } },
  { code: 'MG', name: { ru: 'Мадагаскар', en: 'Madagascar' } },
];

countries.sort((a, b) => a.name.ru.localeCompare(b.name.ru));

export function countryCodeToEmoji(code: string) {
  if (code.startsWith('GB-')) return '🇬🇧';
  return code.replace(/-/g, '').toUpperCase().replace(/./g, (char: string) => String.fromCodePoint(127397 + char.charCodeAt(0)));
} 