import { pgTable, uuid, varchar, text, timestamp, integer } from 'drizzle-orm/pg-core';

export const player = pgTable('Player', {
  id: uuid('id').primaryKey().defaultRandom(),
  firstName: varchar('firstName', { length: 255 }).notNull(),
  lastName: varchar('lastName', { length: 255 }).notNull(),
  middleName: varchar('middleName', { length: 255 }),
  number: integer('number'),
  position: varchar('position', { length: 255 }),
  strongFoot: varchar('strongFoot', { length: 255 }),
  dateOfBirth: timestamp('dateOfBirth', { withTimezone: true }),
  academyJoinDate: timestamp('academyJoinDate', { withTimezone: true }),
  contractStartDate: timestamp('contractStartDate', { withTimezone: true }),
  contractEndDate: timestamp('contractEndDate', { withTimezone: true }),
  nationality: varchar('nationality', { length: 255 }),
  imageUrl: text('imageUrl'),
  status: varchar('status', { length: 255 }),
  birthCertificateNumber: varchar('birthCertificateNumber', { length: 255 }),
  passportData: varchar('passportData', { length: 255 }),
  insuranceNumber: varchar('insuranceNumber', { length: 255 }),
  visaExpiryDate: timestamp('visaExpiryDate', { withTimezone: true }),
  pinCode: varchar('pinCode', { length: 255 }).notNull(),
  telegramId: varchar('telegramId', { length: 255 }).unique(),
  language: varchar('language', { length: 10 }),
  createdAt: timestamp('createdAt', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updatedAt', { withTimezone: true }).defaultNow().notNull(),
  teamId: uuid('teamId').notNull(),
  format1: varchar('format1', { length: 32 }),
  formation1: varchar('formation1', { length: 32 }),
  positionIndex1: integer('positionIndex1'),
  format2: varchar('format2', { length: 32 }),
  formation2: varchar('formation2', { length: 32 }),
  positionIndex2: integer('positionIndex2'),
}); 